# Generated by Django 4.2 on 2023-04-23 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('name_en_us', models.CharField(max_length=150, null=True, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=150, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=150, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('first_name', models.CharField(max_length=150, verbose_name='First name')),
                ('first_name_en_us', models.CharField(max_length=150, null=True, verbose_name='First name')),
                ('first_name_uz', models.CharField(max_length=150, null=True, verbose_name='First name')),
                ('first_name_ru', models.CharField(max_length=150, null=True, verbose_name='First name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last name')),
                ('last_name_en_us', models.CharField(max_length=150, null=True, verbose_name='Last name')),
                ('last_name_uz', models.CharField(max_length=150, null=True, verbose_name='Last name')),
                ('last_name_ru', models.CharField(max_length=150, null=True, verbose_name='Last name')),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.university', verbose_name='University')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
